### ISSUE TITLE
Rendering Sprites

### ISSUE THREAD

**Issue by chevreaux** [chicory-pizza/chicory-data#1]
I'd be nice to render sprites for decorations and objects instead of just text labels. It's probably copyright infringement if we were to just upload all the sprites from the game though. To get around this I've let the user upload sprites which they've extracted with UndertaleModTool themselves. (Sprite alignment and scaling still WIP)

It works but it's certainly not the nicest thing to work with. Thoughts on this feature? Is it even needed or should we just host sprites ourselves?

https://user-images.githubusercontent.com/100559324/156534249-76b12471-0417-4628-a502-c460a9f54836.mp4

**Comment by ngyikp** [comment]
Being able to view decorations would certainly help and this prototype already looks nice! We can add further enhancements such as editing in future update.

(btw, is drawing the decorations really that slow? Might make sense to try loading all sprites first and then draw to canvas, but I don't know will it make initial loading even slower)

As for sprite alignment and scaling, they would likely need to be sourced from `data.win`, no? Maybe it could be generated with a custom script run inside UndertaleModTool

**Comment by chevreaux** [comment]
The drawing isn't slow, the files just take a bit of time to upload at first. Decorations have a xs and ys attribute which I assume is x scale and y scale. Should be able to use that.

I think I will shelve this for now until we've got more work done on decorations & objects. Should be easy to reimplement later on now that I'm familiar with the code.

**Comment by chevreaux** [comment]
Made some improvements to aligning sprites. Most of these look pretty good but there must be some extra data for the lamp post or something.

![image](https://user-images.githubusercontent.com/100559324/157380558-5d207445-6bd3-4985-9234-38179d0058e6.png)

**Comment by ngyikp** [comment]
Do you mean the Z order of the lamp? I'm not sure how the game renders the objects/decos, possibly first to last as back to front

**Comment by chevreaux** [comment]
Nah, I'm currently aligning each sprite at their center, but some sprites like the lamppost have their origins somewhere else. We'd have to get that with a custom script like you said earlier.

In the mean time, a nice alternative could be to have a panel on the side that shows your currently selected object/deco, though that inspector panel is getting a little cramped.

**Comment by ngyikp** [comment]
I plan to merge the level properties with the objects list and make them collapsible, so the decos list can just be below the objects list

**Comment by chevreaux** [comment]
This is fully working, and I just need to fix Flow errors before I can do a PR. It's a headache to say the least. Since components can now accept a GameObjectType or a DecorationType, I need to do type refinement so it works for both. I'm struggling to make that work. Flow type refinement doesn't seem to work too well with JSX. We might be better off just using separate components for objects and decos. If I can't get this working, I'll just push what I've got and let you take a look.
