### ISSUE TITLE
Use File System Access API

### ISSUE THREAD

**Issue by ngyikp** [chicory-pizza/chicory-data#4]
Instead of constantly saving the level_data to the Downloads folder, use this API so you can save directly to the game folder.

This feature is still bleeding-edge so the old download method still needs to be tested.

https://github.com/GoogleChromeLabs/browser-fs-access
https://web.dev/file-system-access/
https://web.dev/browser-fs-access/

**Comment by chevreaux** [comment]
I will look into this, could be useful for working with sprites as well.

**Comment by chevreaux** [comment]
Implemented and this works really nice! Using browser-fs-access I can save directly to my game folder on Chrome while Firefox resorts to the standard downloading method. However the module is untyped so Flow is throwing an error.

**Comment by ngyikp** [comment]
Yeah, feel free to use `// $FlowFixMe[untyped-import]` above the import line

**Comment by ngyikp** [comment]
One annoyance is if the game is installed to a system folder such as Program Files, Chrome will refuse to open/save and show an error "can't open files in this folder because it contains system files".

It's possible to trick this by using `mklink /d` to create a directory symbolic link, but the easiest solution is to tell others to copy the game to another folder, good practice to separate the stock/modded game anyway.
