### ISSUE TITLE
Cannot copy values from color picker 

### ISSUE THREAD

**Issue by PlasmaFlare** [chicory-pizza/chicory-data#56]
Apparently you cannot copy RGB/HSL/Hex values from the color picker. Would be nice for getting exact colors.

<img width="271" alt="image" src="https://user-images.githubusercontent.com/6231645/193429473-2b71ef7b-d81d-49fe-b758-79f129c2369d.png">

**Comment by ngyikp** [comment]
The color picker input comes from the browser, and copying/pasting from it in Chrome is broken for 2+ years: https://bugs.chromium.org/p/chromium/issues/detail?id=1066509

**Comment by PlasmaFlare** [comment]
Welp, guess I better get firefox #calledout
