### ISSUE TITLE
In-game screenshot should not be draggable

### ISSUE THREAD

**Issue by PlasmaFlare** [chicory-pizza/chicory-data#59]
With "Original in-game screenshot" enabled, clicking and dragging around the level editor screen makes the cursor drag and drop the screenshot. While I guess this could be useful if you want to download the image, I feel it's more annoying to use when simply level editing.

Possibly make the in-game screenshot unable to be draggable.

**Comment by ngyikp** [comment]
This is already done at https://github.com/chicory-pizza/chicory-data/blame/7fc98c04e880b9f91076b8c8141efcb3c7056588/src/levelEditor/preview/LevelInGamePreview.jsx#L60-L62 ?
