### ISSUE TITLE
Implement in-browser terrain pixel editor

### ISSUE THREAD

**Issue by ngyikp** [chicory-pizza/chicory-data#6]
Currently editing terrain requires an external image editor, implement an in-browser version for quick edits.

https://www.newline.co/@theabbie/how-to-create-a-pixel-art-editor-using-html5-canvas--2af99b7a
https://github.com/rgab1508/PixelCraft

Building an in-browser version also lets us bypass the imprecise colors that browser canvas has...

https://github.com/chicory-pizza/chicory-data/blob/d71e40302134395147a1a1b8de311d439a6c9b1f/src/terrainEditor/LevelTerrainEditorModal.js#L47-L60

**Comment by chevreaux** [comment]
This would be really nice so I think I will look into it next.

**Comment by chevreaux** [comment]
Got a basic prototype working. Lots of work to be done to get this fully featured, but its looking promising.

![image](https://user-images.githubusercontent.com/100559324/158048568-11a7b2cb-2c9b-46ef-b00e-c5c7d84d1bb5.png)

**Comment by chevreaux** [comment]
List of things to do (might break away into their own issues at a later date)

- Disable object interaction when painting
- Change cursor when in paint mode
- Different brush sizes
- Avoid rendering the whole level inspector every time a pixel is changed

**Comment by ngyikp** [comment]
Nice, I wonder about the performance, if you're directly saving to the level's geo, I imagine the performance would be bad as the geo is constantly encoded and decoded, and the new level data being propagated to all other React components. It might make sense to have the level inspector use a temporary canvas.

**Comment by chevreaux** [comment]
Wanted to give a small update on this

https://user-images.githubusercontent.com/100559324/159877490-a59920a7-1ffe-4762-a5dc-6c4ace8311fe.mp4

It's going pretty good! Still in crappy prototype phase, but it's progressing nicely.

**Comment by ngyikp** [comment]
Looks nice! The performance feels laggy, the new pixel edits should be in a draft state and the geo saved on mouse up, that's how any other image editor app works and would work nicely with the new undo feature.

It would be great to do a rebase and make an early draft PR to ensure the implementation is good.

**Comment by PlasmaFlare** [comment]
Hello! I've taken the liberty to implement this myself. Will link a draft PR soon.
