### ISSUE TITLE
Scaling/rotating objCustomDog doesn't work anymore

### ISSUE THREAD

**Issue by ngyikp** [chicory-pizza/chicory-data#80]
objCustomDog has custom object rendering that has angle/xscale/yscale, but it no longer renders correctly due to https://github.com/chicory-pizza/chicory-data/pull/69

What the old version looked like:
<img width="409" alt="image" src="https://user-images.githubusercontent.com/6135313/229752399-62b55fc3-2fce-45f5-bbab-a53e26cf85f9.png">

The applied CSS properties were `left: 1700px; top: 482px; transform-origin: 75px 130px; transform: translate(-50%, -50%) rotate(-90deg) scaleX(1.5) scaleY(0.5);`, the order of the transform properties matter: https://www.youtube.com/watch?v=azoIMhKOucQ

**Comment by PlasmaFlare** [comment]
I know what the issue is. Will work on this when I get back.
